### ISSUE TITLE
Use the proper vim structure.

### ISSUE THREAD

**Issue by KarlWithK** [pradyungn/dotfiles#2]
Hey, I noticed that you are sourcing a lot in your init.vim, but it seems that your config directory is in your runtimepath. Therefore, I feel like you look up `help runtime`, as it may help your setup.

**Comment by pradyungn** [comment]
Thanks for the heads up! I've redone the init.vim with runtime commands - i'd use a wildcard, but I require the specific order that's done in the file. Otherwise, stuff breaks. If you think that the file could be done better, feel free to reopen the issue!
