### ISSUE TITLE
[EWW]: No window named 'bar' exists

### ISSUE THREAD

**Issue by luigibarbato** [pradyungn/dotfiles#4]
Hello! I wanted to try your fantastic **Hades** theme, I set all the configurations but `eww`, at launch, it does not find neither "launcher" nor "bar" 😔

**Comment by pradyungn** [comment]
weird... can you tell me what you did to install my theme? (sorry about the late response :/)

**Comment by nuzzzen** [comment]
Apparently I have the same issue - I guess it's related to `eww.yuck` file missing from your repo.

EDIT: The launcher won't even start, it's not an icon issue but I don't really know where to seek for errors. I can only see that there's some errors in `ewwmenu` file but I can't understand what to edit.

**Comment by pradyungn** [comment]
I guarantee yoj this is because my configuration is designed for an older version of EWW, and i never took the time to upgrade eww. I'll try looking into migration!

**Comment by nuzzzen** [comment]
Oh ok seems logical. I'm sorry but I never used eww.

**Comment by pradyungn** [comment]
Finally looked into the new eww configuration syntax, and it's gonna take a wihle to port over hte existing XML config - closing this issue for now since there's not really a ton I can do until the config is migrated, and the current config is _technically_ valid, just for an older version of EWW.
